export type Product = {
  id: string;
  slug: string;
  category: string;
  product: string;
  brand: string;
  model: string;
  type: string;
  name: string;
  price: number;
  image: string;
  description: string;
  rating: number;
  reviews: number;
  stock: string;
  discount: number;
};

const basePath = import.meta.env.BASE_URL || "/";

const assetUrl = (image: string) => `${basePath.replace(/\/$/, "")}/${image.replace(/^\//, "")}`;

export const rawProducts = [
  {
    "id": "mobiles-1",
    "slug": "mobiles-oneplus-10-pro-1",
    "category": "Mobiles",
    "product": "Mobile",
    "brand": "OnePlus",
    "model": "10 Pro 5G",
    "type": "",
    "name": "OnePlus 10 Pro 5G",
    "price": 899,
    "image": "assets/NewMobile/1.png",
    "description": "A premium OnePlus smartphone providing a fast and smooth experience.",
    "rating": 4.8,
    "reviews": 261,
    "stock": "Limited stock",
    "discount": 12
  },
  {
    "id": "mobiles-2",
    "slug": "mobiles-oppo-a78-5g-2",
    "category": "Mobiles",
    "product": "Mobile",
    "brand": "OPPO",
    "model": "A78 5G",
    "type": "",
    "name": "OPPO A78 5G",
    "price": 299,
    "image": "assets/NewMobile/2.jpg",
    "description": "An excellent mid-range 5G smartphone from OPPO with reliable battery life.",
    "rating": 4.6,
    "reviews": 308,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "mobiles-3",
    "slug": "mobiles-oneplus-nord-2t-3",
    "category": "Mobiles",
    "product": "Mobile",
    "brand": "OnePlus",
    "model": "Nord 2T",
    "type": "",
    "name": "OnePlus Nord 2T",
    "price": 399,
    "image": "assets/NewMobile/3.jpg",
    "description": "A stylish OnePlus Nord device offering great performance in an eye-catching green.",
    "rating": 4.4,
    "reviews": 355,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "mobiles-4",
    "slug": "mobiles-samsung-galaxy-m13-5g-4",
    "category": "Mobiles",
    "product": "Mobile",
    "brand": "Samsung",
    "model": "Galaxy M13 5G",
    "type": "",
    "name": "Samsung Galaxy M13 5G",
    "price": 249,
    "image": "assets/NewMobile/4.jpg",
    "description": "A budget-friendly Samsung Galaxy with high endurance and 5G connectivity.",
    "rating": 4.2,
    "reviews": 402,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "mobiles-5",
    "slug": "mobiles-vivo-y16-5",
    "category": "Mobiles",
    "product": "Mobile",
    "brand": "Vivo",
    "model": "Y16",
    "type": "",
    "name": "Vivo Y16",
    "price": 199,
    "image": "assets/NewMobile/5.jpg",
    "description": "An affordable Vivo smartphone with a sleek design and a dependable every-day camera.",
    "rating": 4.9,
    "reviews": 449,
    "stock": "In stock",
    "discount": 15
  },
  {
    "id": "mobiles-6",
    "slug": "mobiles-redmi-note-11s-6",
    "category": "Mobiles",
    "product": "Mobile",
    "brand": "Redmi",
    "model": "Note 11S",
    "type": "",
    "name": "Redmi Note 11S",
    "price": 279,
    "image": "assets/NewMobile/6.jpg",
    "description": "A popular Redmi Note device known for its vibrant display and impressive camera array.",
    "rating": 4.7,
    "reviews": 496,
    "stock": "Limited stock",
    "discount": 27
  },
  {
    "id": "mobiles-7",
    "slug": "mobiles-tecno-spark-10-5g-7",
    "category": "Mobiles",
    "product": "Mobile",
    "brand": "Tecno",
    "model": "Spark 10 5G",
    "type": "",
    "name": "Tecno Spark 10 5G",
    "price": 189,
    "image": "assets/NewMobile/7.jpg",
    "description": "A powerful yet affordable 5G entry from Tecno with long-lasting battery.",
    "rating": 4.5,
    "reviews": 543,
    "stock": "In stock",
    "discount": 12
  },
  {
    "id": "mobiles-8",
    "slug": "mobiles-bharat-feature-phone-8",
    "category": "Mobiles",
    "product": "Mobile",
    "brand": "Bharat",
    "model": "Feature Phone",
    "type": "",
    "name": "Bharat Feature Phone",
    "price": 29.99,
    "image": "assets/NewMobile/8.jpg",
    "description": "A durable and simple feature phone perfect for calls, texts, and incredible standby time.",
    "rating": 4.3,
    "reviews": 590,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "mobiles-9",
    "slug": "mobiles-vivo-v25-pro-9",
    "category": "Mobiles",
    "product": "Mobile",
    "brand": "Vivo",
    "model": "V25 Pro",
    "type": "",
    "name": "Vivo V25 Pro",
    "price": 499,
    "image": "assets/NewMobile/9.jpg",
    "description": "A gorgeous smartphone with an elegant back glass design.",
    "rating": 4.1,
    "reviews": 637,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "mobiles-10",
    "slug": "mobiles-vivo-t1-5g-10",
    "category": "Mobiles",
    "product": "Mobile",
    "brand": "Vivo",
    "model": "T1 5G",
    "type": "",
    "name": "Vivo T1 5G",
    "price": 319,
    "image": "assets/NewMobile/10.jpg",
    "description": "A fast and responsive 5G smartphone perfect for everyday multitasking.",
    "rating": 4.8,
    "reviews": 684,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "mobiles-11",
    "slug": "mobiles-oneplus-11r-5g-11",
    "category": "Mobiles",
    "product": "Mobile",
    "brand": "OnePlus",
    "model": "11R 5G",
    "type": "",
    "name": "OnePlus 11R 5G",
    "price": 549,
    "image": "assets/NewMobile/11.jpg",
    "description": "A performance-focused 5G device offering flagship features at a competitive price.",
    "rating": 4.6,
    "reviews": 731,
    "stock": "Limited stock",
    "discount": 15
  },
  {
    "id": "mobiles-12",
    "slug": "mobiles-oppo-reno-8t-12",
    "category": "Mobiles",
    "product": "Mobile",
    "brand": "OPPO",
    "model": "Reno 8T 5G",
    "type": "",
    "name": "OPPO Reno 8T 5G",
    "price": 399,
    "image": "assets/NewMobile/12.jpg",
    "description": "A stylish Reno phone featuring a curved screen and an impressive camera.",
    "rating": 4.4,
    "reviews": 778,
    "stock": "In stock",
    "discount": 27
  },
  {
    "id": "computers-1",
    "slug": "computers-dell-inspiron-15-1",
    "category": "Computers",
    "product": "Computer",
    "brand": "Dell",
    "model": "Inspiron 15",
    "type": "",
    "name": "Dell Inspiron 15",
    "price": 899.99,
    "image": "assets/Computers/12.jpg",
    "description": "A versatile laptop with powerful performance and a sleek design.",
    "rating": 4.1,
    "reviews": 261,
    "stock": "Limited stock",
    "discount": 12
  },
  {
    "id": "computers-2",
    "slug": "computers-hp-pavilion-27-2",
    "category": "Computers",
    "product": "Computer",
    "brand": "HP",
    "model": "Pavilion 27",
    "type": "",
    "name": "HP Pavilion 27",
    "price": 1299,
    "image": "assets/Computers/4.jpg",
    "description": "An all-in-one desktop PC with a large display and high-speed processing.",
    "rating": 4.8,
    "reviews": 308,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "computers-3",
    "slug": "computers-apple-macbook-air-3",
    "category": "Computers",
    "product": "Computer",
    "brand": "Apple",
    "model": "MacBook Air",
    "type": "",
    "name": "Apple MacBook Air",
    "price": 1199,
    "image": "assets/Computers/3.jpg",
    "description": "An ultrathin and lightweight laptop known for its portability and smooth performance.",
    "rating": 4.6,
    "reviews": 355,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "computers-4",
    "slug": "computers-lenovo-ideapad-flex-4",
    "category": "Computers",
    "product": "Computer",
    "brand": "Lenovo",
    "model": "IdeaPad Flex",
    "type": "",
    "name": "Lenovo IdeaPad Flex",
    "price": 799.5,
    "image": "assets/Computers/11.jpg",
    "description": "A flexible 2-in-1 laptop with touchscreen capabilities and powerful processing.",
    "rating": 4.4,
    "reviews": 402,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "computers-5",
    "slug": "computers-acer-predator-helios-300-5",
    "category": "Computers",
    "product": "Computer",
    "brand": "Acer",
    "model": "Predator Helios 300",
    "type": "",
    "name": "Acer Predator Helios 300",
    "price": 1299,
    "image": "assets/Computers/5.jpg",
    "description": "A gaming laptop with high-performance graphics and advanced cooling technology.",
    "rating": 4.2,
    "reviews": 449,
    "stock": "In stock",
    "discount": 15
  },
  {
    "id": "computers-6",
    "slug": "computers-microsoft-surface-pro-7-6",
    "category": "Computers",
    "product": "Computer",
    "brand": "Microsoft",
    "model": "Surface Pro 7",
    "type": "",
    "name": "Microsoft Surface Pro 7",
    "price": 999.99,
    "image": "assets/Computers/6.jpg",
    "description": "A versatile 2-in-1 tablet and laptop with a detachable keyboard and stylus support.",
    "rating": 4.9,
    "reviews": 496,
    "stock": "Limited stock",
    "discount": 27
  },
  {
    "id": "computers-7",
    "slug": "computers-asus-zenbook-14-7",
    "category": "Computers",
    "product": "Computer",
    "brand": "Asus",
    "model": "ZenBook 14",
    "type": "",
    "name": "Asus ZenBook 14",
    "price": 899,
    "image": "assets/Computers/7.jpg",
    "description": "A compact laptop with a premium build, strong performance, and long battery life.",
    "rating": 4.7,
    "reviews": 543,
    "stock": "In stock",
    "discount": 12
  },
  {
    "id": "computers-8",
    "slug": "computers-alienware-aurora-r10-8",
    "category": "Computers",
    "product": "Computer",
    "brand": "Alienware",
    "model": "Aurora R10",
    "type": "",
    "name": "Alienware Aurora R10",
    "price": 1999,
    "image": "assets/Computers/8.jpg",
    "description": "A high-end gaming desktop with customizable components and advanced graphics capabilities.",
    "rating": 4.5,
    "reviews": 590,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "computers-9",
    "slug": "computers-hp-elitebook-840-9",
    "category": "Computers",
    "product": "Computer",
    "brand": "HP",
    "model": "EliteBook 840",
    "type": "",
    "name": "HP EliteBook 840",
    "price": 1299,
    "image": "assets/Computers/9.jpg",
    "description": "A business laptop with robust security features, reliable performance, and sleek design.",
    "rating": 4.3,
    "reviews": 637,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "computers-10",
    "slug": "computers-lenovo-thinkcentre-m720-10",
    "category": "Computers",
    "product": "Computer",
    "brand": "Lenovo",
    "model": "ThinkCentre M720",
    "type": "",
    "name": "Lenovo ThinkCentre M720",
    "price": 799,
    "image": "assets/Computers/10.jpg",
    "description": "A compact and powerful desktop computer suitable for business and productivity tasks.",
    "rating": 4.1,
    "reviews": 684,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "computers-11",
    "slug": "computers-dell-xps-13-11",
    "category": "Computers",
    "product": "Computer",
    "brand": "Dell",
    "model": "XPS 13",
    "type": "",
    "name": "Dell XPS 13",
    "price": 1499,
    "image": "assets/Computers/2.jpg",
    "description": "A premium ultrabook with a stunning display, strong performance, and sleek design.",
    "rating": 4.8,
    "reviews": 731,
    "stock": "Limited stock",
    "discount": 15
  },
  {
    "id": "computers-12",
    "slug": "computers-acer-chromebook-14-12",
    "category": "Computers",
    "product": "Computer",
    "brand": "Acer",
    "model": "Chromebook 14",
    "type": "",
    "name": "Acer Chromebook 14",
    "price": 349.99,
    "image": "assets/Computers/1.jpg",
    "description": "A lightweight and affordable laptop running on Chrome OS, ideal for web-based tasks.",
    "rating": 4.6,
    "reviews": 778,
    "stock": "In stock",
    "discount": 27
  },
  {
    "id": "watches-1",
    "slug": "watches-apple-watch-series-7-1",
    "category": "Watches",
    "product": "Watch",
    "brand": "Apple",
    "model": "Watch Series 7",
    "type": "",
    "name": "Apple Watch Series 7",
    "price": 399,
    "image": "assets/Watch/1.png",
    "description": "The latest Apple Watch with a larger display and advanced health features.",
    "rating": 4.8,
    "reviews": 261,
    "stock": "Limited stock",
    "discount": 12
  },
  {
    "id": "watches-2",
    "slug": "watches-samsung-galaxy-watch-4-2",
    "category": "Watches",
    "product": "Watch",
    "brand": "Samsung",
    "model": "Galaxy Watch 4",
    "type": "",
    "name": "Samsung Galaxy Watch 4",
    "price": 299.99,
    "image": "assets/Watch/2.jpg",
    "description": "A Samsung smartwatch with comprehensive health tracking and versatile design.",
    "rating": 4.6,
    "reviews": 308,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "watches-3",
    "slug": "watches-fitbit-versa-3-3",
    "category": "Watches",
    "product": "Watch",
    "brand": "Fitbit",
    "model": "Versa 3",
    "type": "",
    "name": "Fitbit Versa 3",
    "price": 229,
    "image": "assets/Watch/3.jpg",
    "description": "A Fitbit smartwatch with built-in GPS and fitness tracking capabilities.",
    "rating": 4.4,
    "reviews": 355,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "watches-4",
    "slug": "watches-garmin-forerunner-945-4",
    "category": "Watches",
    "product": "Watch",
    "brand": "Garmin",
    "model": "Forerunner 945",
    "type": "",
    "name": "Garmin Forerunner 945",
    "price": 599.5,
    "image": "assets/Watch/4.jpg",
    "description": "A high-end Garmin GPS watch designed for serious athletes and outdoor enthusiasts.",
    "rating": 4.2,
    "reviews": 402,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "watches-5",
    "slug": "watches-fossil-gen-5-5",
    "category": "Watches",
    "product": "Watch",
    "brand": "Fossil",
    "model": "Gen 5",
    "type": "",
    "name": "Fossil Gen 5",
    "price": 249,
    "image": "assets/Watch/5.jpg",
    "description": "A stylish Fossil smartwatch with Wear OS and customizable watch faces.",
    "rating": 4.9,
    "reviews": 449,
    "stock": "In stock",
    "discount": 15
  },
  {
    "id": "watches-6",
    "slug": "watches-casio-g-shock-ga-2100-6",
    "category": "Watches",
    "product": "Watch",
    "brand": "Casio",
    "model": "G-Shock GA-2100",
    "type": "",
    "name": "Casio G-Shock GA-2100",
    "price": 129.99,
    "image": "assets/Watch/6.jpg",
    "description": "A rugged and iconic G-Shock watch with a modern and slim design.",
    "rating": 4.7,
    "reviews": 496,
    "stock": "Limited stock",
    "discount": 27
  },
  {
    "id": "watches-7",
    "slug": "watches-tag-heuer-carrera-calibre-heuer-02-7",
    "category": "Watches",
    "product": "Watch",
    "brand": "TAG Heuer",
    "model": "Carrera Calibre Heuer 02",
    "type": "",
    "name": "TAG Heuer Carrera Calibre Heuer 02",
    "price": 5999,
    "image": "assets/Watch/7.jpg",
    "description": "A luxurious TAG Heuer mechanical watch with a sporty and sophisticated design.",
    "rating": 4.5,
    "reviews": 543,
    "stock": "In stock",
    "discount": 12
  },
  {
    "id": "watches-8",
    "slug": "watches-timex-weekender-chronograph-8",
    "category": "Watches",
    "product": "Watch",
    "brand": "Timex",
    "model": "Weekender Chronograph",
    "type": "",
    "name": "Timex Weekender Chronograph",
    "price": 89,
    "image": "assets/Watch/8.jpg",
    "description": "A versatile Timex watch with a chronograph function and interchangeable straps.",
    "rating": 4.3,
    "reviews": 590,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "watches-9",
    "slug": "watches-citizen-eco-drive-promaster-9",
    "category": "Watches",
    "product": "Watch",
    "brand": "Citizen",
    "model": "Eco-Drive Promaster",
    "type": "",
    "name": "Citizen Eco-Drive Promaster",
    "price": 299.99,
    "image": "assets/Watch/9.jpg",
    "description": "A Citizen watch powered by light with durable construction for outdoor adventures.",
    "rating": 4.1,
    "reviews": 637,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "watches-10",
    "slug": "watches-seiko-skx007-10",
    "category": "Watches",
    "product": "Watch",
    "brand": "Seiko",
    "model": "SKX007",
    "type": "",
    "name": "Seiko SKX007",
    "price": 199.5,
    "image": "assets/Watch/10.jpg",
    "description": "A classic Seiko diver's watch known for its reliability and timeless design.",
    "rating": 4.8,
    "reviews": 684,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "watches-11",
    "slug": "watches-michael-kors-access-lexington-2-11",
    "category": "Watches",
    "product": "Watch",
    "brand": "Michael Kors",
    "model": "Access Lexington 2",
    "type": "",
    "name": "Michael Kors Access Lexington 2",
    "price": 279,
    "image": "assets/Watch/11.jpg",
    "description": "A Michael Kors smartwatch with a luxurious look and smart functionalities.",
    "rating": 4.6,
    "reviews": 731,
    "stock": "Limited stock",
    "discount": 15
  },
  {
    "id": "watches-12",
    "slug": "watches-huawei-watch-gt-3-12",
    "category": "Watches",
    "product": "Watch",
    "brand": "Huawei",
    "model": "Watch GT 3",
    "type": "",
    "name": "Huawei Watch GT 3",
    "price": 199,
    "image": "assets/Watch/12.jpg",
    "description": "A Huawei smartwatch with long battery life and health monitoring features.",
    "rating": 4.4,
    "reviews": 778,
    "stock": "In stock",
    "discount": 27
  },
  {
    "id": "mens-wear-1",
    "slug": "mens-wear-nike-sporty-tee-1",
    "category": "Mens Wear",
    "product": "Menswear",
    "brand": "Nike",
    "model": "Sporty Tee",
    "type": "T-Shirt",
    "name": "Nike Sporty Tee",
    "price": 29.99,
    "image": "assets/MenWear/1.jpg",
    "description": "A comfortable and stylish sporty t-shirt with moisture-wicking fabric.",
    "rating": 4.1,
    "reviews": 261,
    "stock": "Limited stock",
    "discount": 12
  },
  {
    "id": "mens-wear-2",
    "slug": "mens-wear-calvin-klein-classicfit-2",
    "category": "Mens Wear",
    "product": "Menswear",
    "brand": "Calvin Klein",
    "model": "ClassicFit",
    "type": "Dress Shirt",
    "name": "Calvin Klein ClassicFit",
    "price": 49.99,
    "image": "assets/MenWear/2.jpg",
    "description": "A classic fit dress shirt made from high-quality fabric, suitable for formal occasions.",
    "rating": 4.8,
    "reviews": 308,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "mens-wear-3",
    "slug": "mens-wear-levi-s-511-slim-fit-3",
    "category": "Mens Wear",
    "product": "Menswear",
    "brand": "Levi's",
    "model": "511 Slim Fit",
    "type": "Jeans",
    "name": "Levi's 511 Slim Fit",
    "price": 59.5,
    "image": "assets/MenWear/3.jpg",
    "description": "Slim fit jeans with a modern look, perfect for casual outings.",
    "rating": 4.6,
    "reviews": 355,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "mens-wear-4",
    "slug": "mens-wear-ralph-lauren-signature-polo-4",
    "category": "Mens Wear",
    "product": "Menswear",
    "brand": "Ralph Lauren",
    "model": "Signature Polo",
    "type": "Polo Shirt",
    "name": "Ralph Lauren Signature Polo",
    "price": 69,
    "image": "assets/MenWear/4.jpg",
    "description": "A classic polo shirt with the iconic Ralph Lauren logo, ideal for a refined casual look.",
    "rating": 4.4,
    "reviews": 402,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "mens-wear-5",
    "slug": "mens-wear-the-north-face-apex-bionic-5",
    "category": "Mens Wear",
    "product": "Menswear",
    "brand": "The North Face",
    "model": "Apex Bionic",
    "type": "Jacket",
    "name": "The North Face Apex Bionic",
    "price": 129.99,
    "image": "assets/MenWear/5.jpg",
    "description": "A versatile softshell jacket designed for outdoor activities and everyday wear.",
    "rating": 4.2,
    "reviews": 449,
    "stock": "In stock",
    "discount": 15
  },
  {
    "id": "mens-wear-6",
    "slug": "mens-wear-under-armour-tech-mesh-shorts-6",
    "category": "Mens Wear",
    "product": "Menswear",
    "brand": "Under Armour",
    "model": "Tech Mesh Shorts",
    "type": "Shorts",
    "name": "Under Armour Tech Mesh Shorts",
    "price": 34.99,
    "image": "assets/MenWear/6.jpg",
    "description": "Lightweight and breathable mesh shorts for workouts and active lifestyles.",
    "rating": 4.9,
    "reviews": 496,
    "stock": "Limited stock",
    "discount": 27
  },
  {
    "id": "mens-wear-7",
    "slug": "mens-wear-tommy-hilfiger-crewneck-sweater-7",
    "category": "Mens Wear",
    "product": "Menswear",
    "brand": "Tommy Hilfiger",
    "model": "Crewneck Sweater",
    "type": "Sweater",
    "name": "Tommy Hilfiger Crewneck Sweater",
    "price": 79.5,
    "image": "assets/MenWear/7.jpg",
    "description": "A classic crewneck sweater made from soft and comfortable materials.",
    "rating": 4.7,
    "reviews": 543,
    "stock": "In stock",
    "discount": 12
  },
  {
    "id": "mens-wear-8",
    "slug": "mens-wear-hugo-boss-modernfit-suit-8",
    "category": "Mens Wear",
    "product": "Menswear",
    "brand": "Hugo Boss",
    "model": "ModernFit Suit",
    "type": "Suit",
    "name": "Hugo Boss ModernFit Suit",
    "price": 499,
    "image": "assets/MenWear/8.jpg",
    "description": "A modern-fit suit crafted with attention to detail, perfect for formal occasions.",
    "rating": 4.5,
    "reviews": 590,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "mens-wear-9",
    "slug": "mens-wear-adidas-essentials-hoodie-9",
    "category": "Mens Wear",
    "product": "Menswear",
    "brand": "Adidas",
    "model": "Essentials Hoodie",
    "type": "Hoodie",
    "name": "Adidas Essentials Hoodie",
    "price": 44.99,
    "image": "assets/MenWear/9.jpg",
    "description": "A comfortable and stylish hoodie with the Adidas logo, suitable for everyday wear.",
    "rating": 4.3,
    "reviews": 637,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "mens-wear-10",
    "slug": "mens-wear-dockers-alpha-khaki-10",
    "category": "Mens Wear",
    "product": "Menswear",
    "brand": "Dockers",
    "model": "Alpha Khaki",
    "type": "Chinos",
    "name": "Dockers Alpha Khaki",
    "price": 39.99,
    "image": "assets/MenWear/10.jpg",
    "description": "Versatile chino pants with a modern slim fit, suitable for casual and semi-formal occasions.",
    "rating": 4.1,
    "reviews": 684,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "mens-wear-11",
    "slug": "mens-wear-speedo-endurance-swim-trunks-11",
    "category": "Mens Wear",
    "product": "Menswear",
    "brand": "Speedo",
    "model": "Endurance+ Swim Trunks",
    "type": "Swim Trunks",
    "name": "Speedo Endurance+ Swim Trunks",
    "price": 29.5,
    "image": "assets/MenWear/11.jpg",
    "description": "Durable and comfortable swim trunks designed for performance and comfort in the water.",
    "rating": 4.8,
    "reviews": 731,
    "stock": "Limited stock",
    "discount": 15
  },
  {
    "id": "mens-wear-12",
    "slug": "mens-wear-brothers-classic-blazer-12",
    "category": "Mens Wear",
    "product": "Menswear",
    "brand": "Brothers",
    "model": "Classic Blazer",
    "type": "Blazer",
    "name": "Brothers Classic Blazer",
    "price": 189,
    "image": "assets/MenWear/12.jpg",
    "description": "A timeless classic blazer suitable for both professional and smart-casual looks.",
    "rating": 4.6,
    "reviews": 778,
    "stock": "In stock",
    "discount": 27
  },
  {
    "id": "woman-wear-1",
    "slug": "woman-wear-zara-flowy-maxi-1",
    "category": "Woman Wear",
    "product": "Woman Wear",
    "brand": "Zara",
    "model": "Flowy Maxi",
    "type": "Dress",
    "name": "Zara Flowy Maxi",
    "price": 79.99,
    "image": "assets/Woman/1.jpg",
    "description": "A flowy maxi dress with floral patterns, perfect for summer occasions.",
    "rating": 4.2,
    "reviews": 261,
    "stock": "Limited stock",
    "discount": 12
  },
  {
    "id": "woman-wear-2",
    "slug": "woman-wear-handm-classic-silk-2",
    "category": "Woman Wear",
    "product": "Woman Wear",
    "brand": "H&M",
    "model": "Classic Silk",
    "type": "Blouse",
    "name": "H&M Classic Silk",
    "price": 49.9,
    "image": "assets/Woman/2.jpg",
    "description": "A classic silk blouse suitable for professional and casual settings.",
    "rating": 4.9,
    "reviews": 308,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "woman-wear-3",
    "slug": "woman-wear-levi-s-501-skinny-3",
    "category": "Woman Wear",
    "product": "Woman Wear",
    "brand": "Levi's",
    "model": "501 Skinny",
    "type": "Jeans",
    "name": "Levi's 501 Skinny",
    "price": 89.5,
    "image": "assets/Woman/3.jpg",
    "description": "Skinny fit jeans with a classic 5-pocket design, perfect for everyday wear.",
    "rating": 4.7,
    "reviews": 355,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "woman-wear-4",
    "slug": "woman-wear-forever-21-utility-jumpsuit-4",
    "category": "Woman Wear",
    "product": "Woman Wear",
    "brand": "Forever 21",
    "model": "Utility Jumpsuit",
    "type": "Jumpsuit",
    "name": "Forever 21 Utility Jumpsuit",
    "price": 59.99,
    "image": "assets/Woman/4.jpg",
    "description": "A utility-style jumpsuit with a modern and versatile look.",
    "rating": 4.5,
    "reviews": 402,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "woman-wear-5",
    "slug": "woman-wear-topshop-a-line-mini-5",
    "category": "Woman Wear",
    "product": "Woman Wear",
    "brand": "Topshop",
    "model": "A-Line Mini",
    "type": "Skirt",
    "name": "Topshop A-Line Mini",
    "price": 39.99,
    "image": "assets/Woman/5.jpg",
    "description": "A stylish A-line mini skirt with a retro touch, suitable for various occasions.",
    "rating": 4.3,
    "reviews": 449,
    "stock": "In stock",
    "discount": 15
  },
  {
    "id": "woman-wear-6",
    "slug": "woman-wear-gap-cable-knit-6",
    "category": "Woman Wear",
    "product": "Woman Wear",
    "brand": "Gap",
    "model": "Cable Knit",
    "type": "Sweater",
    "name": "Gap Cable Knit",
    "price": 49.95,
    "image": "assets/Woman/6.jpg",
    "description": "A cozy cable knit sweater with a timeless design, perfect for chilly days.",
    "rating": 4.1,
    "reviews": 496,
    "stock": "Limited stock",
    "discount": 27
  },
  {
    "id": "woman-wear-7",
    "slug": "woman-wear-mango-tailored-blazer-7",
    "category": "Woman Wear",
    "product": "Woman Wear",
    "brand": "Mango",
    "model": "Tailored Blazer",
    "type": "Blazer",
    "name": "Mango Tailored Blazer",
    "price": 79.99,
    "image": "assets/Woman/7.jpg",
    "description": "A tailored blazer with a chic silhouette, suitable for formal and casual looks.",
    "rating": 4.8,
    "reviews": 543,
    "stock": "In stock",
    "discount": 12
  },
  {
    "id": "woman-wear-8",
    "slug": "woman-wear-lululemon-align-leggings-8",
    "category": "Woman Wear",
    "product": "Woman Wear",
    "brand": "Lululemon",
    "model": "Align Leggings",
    "type": "Activewear",
    "name": "Lululemon Align Leggings",
    "price": 98,
    "image": "assets/Woman/8.jpg",
    "description": "High-quality leggings with a buttery soft feel, ideal for yoga and workouts.",
    "rating": 4.6,
    "reviews": 590,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "woman-wear-9",
    "slug": "woman-wear-secret-bikini-set-9",
    "category": "Woman Wear",
    "product": "Woman Wear",
    "brand": "Secret",
    "model": "Bikini Set",
    "type": "Swimwear",
    "name": "Secret Bikini Set",
    "price": 59.5,
    "image": "assets/Woman/8.jpg",
    "description": "A stylish bikini set with vibrant patterns, perfect for beach days.",
    "rating": 4.4,
    "reviews": 637,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "woman-wear-10",
    "slug": "woman-wear-hollister-high-rise-skinny-10",
    "category": "Woman Wear",
    "product": "Woman Wear",
    "brand": "Hollister",
    "model": "High-Rise Skinny",
    "type": "Pants",
    "name": "Hollister High-Rise Skinny",
    "price": 49.95,
    "image": "assets/Woman/10.jpg",
    "description": "High-rise skinny pants with a flattering fit, suitable for various occasions.",
    "rating": 4.2,
    "reviews": 684,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "woman-wear-11",
    "slug": "woman-wear-voltaire-wool-blend-coat-11",
    "category": "Woman Wear",
    "product": "Woman Wear",
    "brand": "Voltaire",
    "model": "Wool Blend Coat",
    "type": "Coat",
    "name": "Voltaire Wool Blend Coat",
    "price": 299,
    "image": "assets/Woman/11.jpg",
    "description": "A stylish wool blend coat with a modern and elegant design, perfect for colder days.",
    "rating": 4.9,
    "reviews": 731,
    "stock": "Limited stock",
    "discount": 15
  },
  {
    "id": "woman-wear-12",
    "slug": "woman-wear-eagle-graphic-tee-12",
    "category": "Woman Wear",
    "product": "Woman Wear",
    "brand": "Eagle",
    "model": "Graphic Tee",
    "type": "T-Shirt",
    "name": "Eagle Graphic Tee",
    "price": 24.95,
    "image": "assets/Woman/12.jpg",
    "description": "A casual graphic tee with trendy prints, suitable for relaxed everyday outfits.",
    "rating": 4.7,
    "reviews": 778,
    "stock": "In stock",
    "discount": 27
  },
  {
    "id": "furniture-1",
    "slug": "furniture-ikea-comfortplus-1",
    "category": "Furniture",
    "product": "Furniture",
    "brand": "IKEA",
    "model": "ComfortPlus",
    "type": "Sofa",
    "name": "IKEA ComfortPlus",
    "price": 499.99,
    "image": "assets/Furniture/1.jpg",
    "description": "A comfortable and modern sofa with plush cushions and a sleek design.",
    "rating": 4.1,
    "reviews": 261,
    "stock": "Limited stock",
    "discount": 12
  },
  {
    "id": "furniture-2",
    "slug": "furniture-wayfair-elegantdine-2",
    "category": "Furniture",
    "product": "Furniture",
    "brand": "Wayfair",
    "model": "ElegantDine",
    "type": "Dining Table",
    "name": "Wayfair ElegantDine",
    "price": 899,
    "image": "assets/Furniture/2.jpg",
    "description": "An elegant dining table with solid wood construction and expandable design.",
    "rating": 4.8,
    "reviews": 308,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "furniture-3",
    "slug": "furniture-ashley-dreamrest-3",
    "category": "Furniture",
    "product": "Furniture",
    "brand": "Ashley ",
    "model": "DreamRest",
    "type": "Bed",
    "name": "Ashley  DreamRest",
    "price": 799.5,
    "image": "assets/Furniture/3.jpg",
    "description": "A stylish and comfortable bed with upholstered headboard and durable frame.",
    "rating": 4.6,
    "reviews": 355,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "furniture-4",
    "slug": "furniture-west-elm-modernblend-4",
    "category": "Furniture",
    "product": "Furniture",
    "brand": "West Elm",
    "model": "ModernBlend",
    "type": "Coffee Table",
    "name": "West Elm ModernBlend",
    "price": 349.99,
    "image": "assets/Furniture/4.jpg",
    "description": "A modern coffee table with a blend of materials, adding character to your living room.",
    "rating": 4.4,
    "reviews": 402,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "furniture-5",
    "slug": "furniture-houzz-spacesaver-5",
    "category": "Furniture",
    "product": "Furniture",
    "brand": "Houzz",
    "model": "SpaceSaver",
    "type": "Wardrobe",
    "name": "Houzz SpaceSaver",
    "price": 599,
    "image": "assets/Furniture/5.jpg",
    "description": "A space-saving wardrobe with versatile storage compartments and sleek appearance.",
    "rating": 4.2,
    "reviews": 449,
    "stock": "In stock",
    "discount": 15
  },
  {
    "id": "furniture-6",
    "slug": "furniture-crate-and-barrel-bookhaven-6",
    "category": "Furniture",
    "product": "Furniture",
    "brand": "Crate & Barrel",
    "model": "BookHaven",
    "type": "Bookshelf",
    "name": "Crate & Barrel BookHaven",
    "price": 299.5,
    "image": "assets/Furniture/6.jpg",
    "description": "A functional bookshelf with adjustable shelves, suitable for any room.",
    "rating": 4.9,
    "reviews": 496,
    "stock": "Limited stock",
    "discount": 27
  },
  {
    "id": "furniture-7",
    "slug": "furniture-staples-workpro-7",
    "category": "Furniture",
    "product": "Furniture",
    "brand": "Staples",
    "model": "WorkPro",
    "type": "Desk",
    "name": "Staples WorkPro",
    "price": 199.99,
    "image": "assets/Furniture/7.jpg",
    "description": "A spacious office desk with ergonomic design and ample storage.",
    "rating": 4.7,
    "reviews": 543,
    "stock": "In stock",
    "discount": 12
  },
  {
    "id": "furniture-8",
    "slug": "furniture-target-urbanchic-8",
    "category": "Furniture",
    "product": "Furniture",
    "brand": "Target",
    "model": "UrbanChic",
    "type": "Bar Stool",
    "name": "Target UrbanChic",
    "price": 89,
    "image": "assets/Furniture/8.jpg",
    "description": "An urban chic bar stool with a contemporary look, perfect for kitchen islands.",
    "rating": 4.5,
    "reviews": 590,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "furniture-9",
    "slug": "furniture-pottery-barn-rusticcharm-9",
    "category": "Furniture",
    "product": "Furniture",
    "brand": "Pottery Barn",
    "model": "RusticCharm",
    "type": "Dresser",
    "name": "Pottery Barn RusticCharm",
    "price": 599.99,
    "image": "assets/Furniture/9.jpg",
    "description": "A rustic dresser with ample storage space and charming distressed finish.",
    "rating": 4.3,
    "reviews": 637,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "furniture-10",
    "slug": "furniture-crate-and-barrel-comfylounge-10",
    "category": "Furniture",
    "product": "Furniture",
    "brand": "Crate & Barrel",
    "model": "ComfyLounge",
    "type": "Couch",
    "name": "Crate & Barrel ComfyLounge",
    "price": 999,
    "image": "assets/Furniture/10.jpg",
    "description": "A comfortable couch with deep seating and modern design, perfect for lounging.",
    "rating": 4.1,
    "reviews": 684,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "furniture-11",
    "slug": "furniture-cb2-minimalistside-11",
    "category": "Furniture",
    "product": "Furniture",
    "brand": "CB2",
    "model": "MinimalistSide",
    "type": "Side Table",
    "name": "CB2 MinimalistSide",
    "price": 149.5,
    "image": "assets/Furniture/11.jpg",
    "description": "A minimalist side table with clean lines, adding functionality to any space.",
    "rating": 4.8,
    "reviews": 731,
    "stock": "Limited stock",
    "discount": 15
  },
  {
    "id": "furniture-12",
    "slug": "furniture-ethan-allen-classicnight-12",
    "category": "Furniture",
    "product": "Furniture",
    "brand": "Ethan Allen",
    "model": "ClassicNight",
    "type": "Bedside Table",
    "name": "Ethan Allen ClassicNight",
    "price": 249,
    "image": "assets/Furniture/12.jpg",
    "description": "A classic bedside table with a timeless design and convenient storage.",
    "rating": 4.6,
    "reviews": 778,
    "stock": "In stock",
    "discount": 27
  },
  {
    "id": "ac-1",
    "slug": "ac-lg-cooltech-5000-1",
    "category": "AC",
    "product": "Air Conditioner",
    "brand": "Hisense",
    "model": "CoolTech 5000",
    "type": "",
    "name": "Hisense CoolTech 5000",
    "price": 799.99,
    "image": "assets/Ac/1.jpg",
    "description": "Powerful 15000 BTU window air conditioner with energy-saving features.",
    "rating": 4.3,
    "reviews": 261,
    "stock": "Limited stock",
    "discount": 12
  },
  {
    "id": "ac-2",
    "slug": "ac-daikin-climatemaster-pro-2",
    "category": "AC",
    "product": "AC Unit",
    "brand": "Daikin",
    "model": "ClimateMaster Pro",
    "type": "",
    "name": "Daikin ClimateMaster Pro",
    "price": 1299,
    "image": "assets/Ac/2.jpg",
    "description": "Advanced split-system AC with smart temperature control and quiet operation.",
    "rating": 4.1,
    "reviews": 308,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "ac-3",
    "slug": "ac-carrier-arctic-breeze-300-3",
    "category": "AC",
    "product": "Cooling System",
    "brand": "LG",
    "model": "Arctic Breeze 300",
    "type": "",
    "name": "LG Arctic Breeze 300",
    "price": 899.99,
    "image": "assets/Ac/3.jpg",
    "description": "Ductless mini-split AC with adjustable airflow and dehumidification.",
    "rating": 4.8,
    "reviews": 355,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "ac-4",
    "slug": "ac-honeywell-frostflow-xl-4",
    "category": "AC",
    "product": "Air Cooler",
    "brand": "LLoyd",
    "model": "FrostFlow XL",
    "type": "",
    "name": "LLoyd FrostFlow XL",
    "price": 299.5,
    "image": "assets/Ac/4.jpg",
    "description": "Portable evaporative cooler with large water tank for efficient cooling in dry climates.",
    "rating": 4.6,
    "reviews": 402,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "ac-5",
    "slug": "ac-whirlpool-chillguard-800-5",
    "category": "AC",
    "product": "Window AC",
    "brand": "Haier",
    "model": "ChillGuard 800",
    "type": "",
    "name": "Haier ChillGuard 800",
    "price": 549,
    "image": "assets/Ac/5.jpg",
    "description": "Energy-efficient window-mounted air conditioner with remote control.",
    "rating": 4.4,
    "reviews": 449,
    "stock": "In stock",
    "discount": 15
  },
  {
    "id": "ac-6",
    "slug": "ac-nest-ecocool-smart-6",
    "category": "AC",
    "product": "Smart AC",
    "brand": "Whirlpool",
    "model": "EcoCool Smart+",
    "type": "",
    "name": "Whirlpool EcoCool Smart+",
    "price": 899.99,
    "image": "assets/Ac/6.jpg",
    "description": "Wi-Fi connected smart AC that adapts to your cooling preferences and schedule.",
    "rating": 4.2,
    "reviews": 496,
    "stock": "Limited stock",
    "discount": 27
  },
  {
    "id": "ac-7",
    "slug": "ac-mitsubishi-silentcomfort-1200i-7",
    "category": "AC",
    "product": "Inverter AC",
    "brand": "Mitsubishi",
    "model": "SilentComfort 1200i",
    "type": "",
    "name": "Mitsubishi SilentComfort 1200i",
    "price": 1499,
    "image": "assets/Ac/7.jpg",
    "description": "Inverter technology AC with precise temperature control and energy efficiency.",
    "rating": 4.9,
    "reviews": 543,
    "stock": "In stock",
    "discount": 12
  },
  {
    "id": "ac-8",
    "slug": "ac-frigidaire-ezcool-portable-400-8",
    "category": "AC",
    "product": "Portable AC",
    "brand": "Carrier",
    "model": "EZCool Portable 400",
    "type": "",
    "name": "Carrier EZCool Portable 400",
    "price": 399.99,
    "image": "assets/Ac/8.jpg",
    "description": "Easy-to-move portable air conditioner with quick installation and cooling.",
    "rating": 4.7,
    "reviews": 590,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "ac-9",
    "slug": "ac-lennox-pureair-ducted-6000-9",
    "category": "AC",
    "product": "Ducted AC",
    "brand": "Lennox",
    "model": "PureAir Ducted 6000",
    "type": "",
    "name": "Lennox PureAir Ducted 6000",
    "price": 2499,
    "image": "assets/Ac/9.jpg",
    "description": "Whole-house ducted AC system with advanced air purification technology.",
    "rating": 4.5,
    "reviews": 637,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "ac-10",
    "slug": "ac-panasonic-wallmaster-pro-1800-10",
    "category": "AC",
    "product": "Wall-Mount AC",
    "brand": "Panasonic",
    "model": "WallMaster Pro 1800",
    "type": "",
    "name": "Panasonic WallMaster Pro 1800",
    "price": 749,
    "image": "assets/Ac/10.jpg",
    "description": "Wall-mounted AC with adjustable louvers and energy-saving features.",
    "rating": 4.3,
    "reviews": 684,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "ac-11",
    "slug": "ac-haier-coolwave-split-220-11",
    "category": "AC",
    "product": "Split AC",
    "brand": "BPL",
    "model": "CoolWave Split 220",
    "type": "",
    "name": "BPL CoolWave Split 220",
    "price": 649.5,
    "image": "assets/Ac/11.jpg",
    "description": "High-performance split AC system with rapid cooling and remote control.",
    "rating": 4.1,
    "reviews": 731,
    "stock": "Limited stock",
    "discount": 15
  },
  {
    "id": "ac-12",
    "slug": "ac-trane-climatecentral-5000-12",
    "category": "AC",
    "product": "Central AC",
    "brand": "Blue Star",
    "model": "ClimateCentral 5000",
    "type": "",
    "name": "Blue Star ClimateCentral 5000",
    "price": 2999,
    "image": "assets/Ac/12.jpg",
    "description": "Powerful central AC unit for large homes with zone-based temperature control.",
    "rating": 4.8,
    "reviews": 778,
    "stock": "In stock",
    "discount": 27
  },
  {
    "id": "kitchen-1",
    "slug": "kitchen-vitamix-powerblend-5000-1",
    "category": "Kitchen",
    "product": "Kitchen",
    "brand": "LG",
    "model": "PowerBlend 5000",
    "type": "Blender",
    "name": "LG PowerBlend 5000",
    "price": 249.99,
    "image": "assets/Kitchen/1.jpg",
    "description": "A powerful blender for smoothies, soups, and more, with variable speed control.",
    "rating": 4.8,
    "reviews": 261,
    "stock": "Limited stock",
    "discount": 12
  },
  {
    "id": "kitchen-2",
    "slug": "kitchen-calphalon-classic-nonstick-2",
    "category": "Kitchen",
    "product": "Kitchen",
    "brand": "Calphalon",
    "model": "Classic Nonstick",
    "type": "Cookware Set",
    "name": "Calphalon Classic Nonstick",
    "price": 299,
    "image": "assets/Kitchen/2.jpg",
    "description": "A comprehensive cookware set featuring nonstick surfaces and durable construction.",
    "rating": 4.6,
    "reviews": 308,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "kitchen-3",
    "slug": "kitchen-keurig-k-elite-3",
    "category": "Kitchen",
    "product": "Kitchen",
    "brand": "Keurig",
    "model": "K-Elite",
    "type": "Coffee Maker",
    "name": "Keurig K-Elite",
    "price": 149.5,
    "image": "assets/Kitchen/3.jpg",
    "description": "A versatile coffee maker with multiple brew sizes and strong brew option.",
    "rating": 4.4,
    "reviews": 355,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "kitchen-4",
    "slug": "kitchen-wusthof-classic-knife-block-4",
    "category": "Kitchen",
    "product": "Kitchen",
    "brand": "Panasonic",
    "model": "Electric Rice Cooker",
    "type": "Knife Set",
    "name": "Panasonic Electric Rice Cooker",
    "price": 199.99,
    "image": "assets/Kitchen/4.jpg",
    "description": "An affordable and extremely popular standard model. It features a stainless steel lid and thermal fuse protection for safety.",
    "rating": 4.2,
    "reviews": 402,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "kitchen-5",
    "slug": "kitchen-kitchenaid-artisan-series-5",
    "category": "Kitchen",
    "product": "Kitchen",
    "brand": "KitchenAid",
    "model": "Artisan Series",
    "type": "Stand Mixer",
    "name": "KitchenAid Artisan Series",
    "price": 299,
    "image": "assets/Kitchen/5.jpg",
    "description": "An iconic stand mixer known for its versatility and wide range of attachments.",
    "rating": 4.9,
    "reviews": 449,
    "stock": "In stock",
    "discount": 15
  },
  {
    "id": "kitchen-6",
    "slug": "kitchen-pyrex-bake-and-store-6",
    "category": "Kitchen",
    "product": "Kitchen",
    "brand": "Philips",
    "model": "Bake & Store",
    "type": "Baking Set",
    "name": "Philips Bake & Store",
    "price": 49.99,
    "image": "assets/Kitchen/6.png",
    "description": "A practical baking set with various glass containers for baking, storing, and serving.",
    "rating": 4.7,
    "reviews": 496,
    "stock": "Limited stock",
    "discount": 27
  },
  {
    "id": "kitchen-7",
    "slug": "kitchen-zojirushi-neuro-fuzzy-7",
    "category": "Kitchen",
    "product": "Kitchen",
    "brand": "Zojirushi",
    "model": "Neuro Fuzzy",
    "type": "Rice Cooker",
    "name": "Zojirushi Neuro Fuzzy",
    "price": 119,
    "image": "assets/Kitchen/7.jpg",
    "description": "A sophisticated rice cooker with advanced fuzzy logic technology for perfect rice every time.",
    "rating": 4.5,
    "reviews": 543,
    "stock": "In stock",
    "discount": 12
  },
  {
    "id": "kitchen-8",
    "slug": "kitchen-oxo-good-grips-8",
    "category": "Kitchen",
    "product": "Kitchen",
    "brand": "OXO",
    "model": "Good Grips",
    "type": "Utensil Set",
    "name": "OXO Good Grips",
    "price": 29.99,
    "image": "assets/Kitchen/8.jpg",
    "description": "A versatile utensil set with comfortable grips and a variety of kitchen tools.",
    "rating": 4.3,
    "reviews": 590,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "kitchen-9",
    "slug": "kitchen-cuisinart-dlc-8sbcy-9",
    "category": "Kitchen",
    "product": "Kitchen",
    "brand": "Primero",
    "model": "DLC-8SBCY",
    "type": "Food Processor",
    "name": "Primero DLC-8SBCY",
    "price": 129.99,
    "image": "assets/Kitchen/9.jpg",
    "description": "A powerful food processor for chopping, slicing, and shredding ingredients.",
    "rating": 4.1,
    "reviews": 637,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "kitchen-10",
    "slug": "kitchen-oxo-handheld-mixer-10",
    "category": "Kitchen",
    "product": "Kitchen",
    "brand": "OXO",
    "model": "Handheld Mixer",
    "type": "Mixer",
    "name": "OXO Handheld Mixer",
    "price": 49.5,
    "image": "assets/Kitchen/10.jpg",
    "description": "A handheld mixer with multiple speed settings for blending, whipping, and mixing.",
    "rating": 4.8,
    "reviews": 684,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "kitchen-11",
    "slug": "kitchen-corelle-classic-winter-frost-11",
    "category": "Kitchen",
    "product": "Kitchen",
    "brand": "Corelle",
    "model": "Classic Winter Frost",
    "type": "Dish Set",
    "name": "Corelle Classic Winter Frost",
    "price": 69.99,
    "image": "assets/Kitchen/11.jpg",
    "description": "A durable and lightweight dish set suitable for everyday dining and special occasions.",
    "rating": 4.6,
    "reviews": 731,
    "stock": "Limited stock",
    "discount": 15
  },
  {
    "id": "kitchen-12",
    "slug": "kitchen-crock-pot-programmable-slow-cooker-12",
    "category": "Kitchen",
    "product": "Kitchen",
    "brand": "Crock-Pot",
    "model": "Programmable Slow Cooker",
    "type": "Slow Cooker",
    "name": "Crock-Pot Programmable Slow Cooker",
    "price": 79,
    "image": "assets/Kitchen/12.jpg",
    "description": "A programmable slow cooker for convenient and flavorful cooking.",
    "rating": 4.4,
    "reviews": 778,
    "stock": "In stock",
    "discount": 27
  },
  {
    "id": "fridge-1",
    "slug": "fridge-lg-coolfrost-5000-1",
    "category": "Fridge",
    "product": "Refrigerator",
    "brand": "LG",
    "model": "CoolFrost 5000",
    "type": "",
    "name": "LG CoolFrost 5000",
    "price": 999.99,
    "image": "assets/fridge/1.jpg",
    "description": "A spacious and energy-efficient refrigerator with advanced cooling technology.",
    "rating": 4.7,
    "reviews": 261,
    "stock": "Limited stock",
    "discount": 12
  },
  {
    "id": "fridge-2",
    "slug": "fridge-samsung-fridgemaster-pro-2",
    "category": "Fridge",
    "product": "Refrigerator",
    "brand": "Samsung",
    "model": "FridgeMaster Pro",
    "type": "",
    "name": "Samsung FridgeMaster Pro",
    "price": 1499,
    "image": "assets/fridge/2.jpg",
    "description": "A high-capacity refrigerator with smart features and precise temperature control.",
    "rating": 4.5,
    "reviews": 308,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "fridge-3",
    "slug": "fridge-whirlpool-chillzone-300-3",
    "category": "Fridge",
    "product": "Refrigerator",
    "brand": "Whirlpool",
    "model": "ChillZone 300",
    "type": "",
    "name": "Whirlpool ChillZone 300",
    "price": 899.99,
    "image": "assets/fridge/3.jpg",
    "description": "A modern refrigerator with adjustable shelves and efficient cooling performance.",
    "rating": 4.3,
    "reviews": 355,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "fridge-4",
    "slug": "fridge-frigidaire-coolmist-xl-4",
    "category": "Fridge",
    "product": "Refrigerator",
    "brand": "Frigidaire",
    "model": "CoolMist XL",
    "type": "",
    "name": "Frigidaire CoolMist XL",
    "price": 599.5,
    "image": "assets/fridge/4.jpg",
    "description": "A spacious fridge with a water dispenser and innovative humidity control.",
    "rating": 4.1,
    "reviews": 402,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "fridge-5",
    "slug": "fridge-kitchenaid-freezeguard-800-5",
    "category": "Fridge",
    "product": "Refrigerator",
    "brand": "KitchenAid",
    "model": "FreezeGuard 800",
    "type": "",
    "name": "KitchenAid FreezeGuard 800",
    "price": 799,
    "image": "assets/fridge/5.jpg",
    "description": "A premium refrigerator with customizable compartments and stylish design.",
    "rating": 4.8,
    "reviews": 449,
    "stock": "In stock",
    "discount": 15
  },
  {
    "id": "fridge-6",
    "slug": "fridge-ge-smartcool-6",
    "category": "Fridge",
    "product": "Refrigerator",
    "brand": "GE",
    "model": "SmartCool+",
    "type": "",
    "name": "GE SmartCool+",
    "price": 1199.99,
    "image": "assets/fridge/6.jpg",
    "description": "A smart refrigerator with Wi-Fi connectivity and built-in voice control.",
    "rating": 4.6,
    "reviews": 496,
    "stock": "Limited stock",
    "discount": 27
  },
  {
    "id": "fridge-7",
    "slug": "fridge-maytag-icemaster-1500-7",
    "category": "Fridge",
    "product": "Refrigerator",
    "brand": "Maytag",
    "model": "IceMaster 1500",
    "type": "",
    "name": "Maytag IceMaster 1500",
    "price": 1399,
    "image": "assets/fridge/7.jpg",
    "description": "A reliable refrigerator with spacious freezer and high-capacity ice maker.",
    "rating": 4.4,
    "reviews": 543,
    "stock": "In stock",
    "discount": 12
  },
  {
    "id": "fridge-8",
    "slug": "fridge-bosch-freshsense-400-8",
    "category": "Fridge",
    "product": "Refrigerator",
    "brand": "Bosch",
    "model": "FreshSense 400",
    "type": "",
    "name": "Bosch FreshSense 400",
    "price": 999,
    "image": "assets/fridge/8.jpg",
    "description": "A European-style refrigerator with advanced temperature management and energy efficiency.",
    "rating": 4.2,
    "reviews": 590,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "fridge-9",
    "slug": "fridge-haier-coolwave-french-door-9",
    "category": "Fridge",
    "product": "Refrigerator",
    "brand": "Haier",
    "model": "CoolWave French Door",
    "type": "",
    "name": "Haier CoolWave French Door",
    "price": 1699.5,
    "image": "assets/fridge/9.jpg",
    "description": "A French door refrigerator with sleek design and ample storage space.",
    "rating": 4.9,
    "reviews": 637,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "fridge-10",
    "slug": "fridge-sub-zero-prochill-8000-10",
    "category": "Fridge",
    "product": "Refrigerator",
    "brand": "Sub-Zero",
    "model": "ProChill 8000",
    "type": "",
    "name": "Sub-Zero ProChill 8000",
    "price": 2999,
    "image": "assets/fridge/10.jpg",
    "description": "A high-end refrigerator with dual cooling zones and advanced preservation features.",
    "rating": 4.7,
    "reviews": 684,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "fridge-11",
    "slug": "fridge-kenmore-elite-series-11",
    "category": "Fridge",
    "product": "Refrigerator",
    "brand": "Kenmore",
    "model": "Elite Series",
    "type": "",
    "name": "Kenmore Elite Series",
    "price": 1199,
    "image": "assets/fridge/11.jpg",
    "description": "An energy-efficient refrigerator with modern features and elegant stainless steel finish.",
    "rating": 4.5,
    "reviews": 731,
    "stock": "Limited stock",
    "discount": 15
  },
  {
    "id": "fridge-12",
    "slug": "fridge-viking-professional-series-12",
    "category": "Fridge",
    "product": "Refrigerator",
    "brand": "Viking",
    "model": "Professional Series",
    "type": "",
    "name": "Viking Professional Series",
    "price": 3999.99,
    "image": "assets/fridge/12.jpg",
    "description": "A high-performance refrigerator designed for professional-grade kitchen environments.",
    "rating": 4.3,
    "reviews": 778,
    "stock": "In stock",
    "discount": 27
  },
  {
    "id": "books-1",
    "slug": "books-how-to-stop-worrying-1",
    "category": "Books",
    "product": "Book",
    "brand": "Dale Carnegie",
    "model": "Paperback",
    "type": "",
    "name": "How to Stop Worrying and Start Living",
    "price": 12.99,
    "image": "assets/Books/1.jpg",
    "description": "Time-tested methods for conquering worry and living a fulfilling life.",
    "rating": 4.6,
    "reviews": 261,
    "stock": "Limited stock",
    "discount": 12
  },
  {
    "id": "books-2",
    "slug": "books-you-can-2",
    "category": "Books",
    "product": "Book",
    "brand": "George Matthew Adams",
    "model": "Paperback",
    "type": "",
    "name": "You Can",
    "price": 10.5,
    "image": "assets/Books/2.jpg",
    "description": "An inspiring guide to self-improvement and achieving your potential.",
    "rating": 4.4,
    "reviews": 308,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "books-3",
    "slug": "books-rich-dad-poor-dad-3",
    "category": "Books",
    "product": "Book",
    "brand": "Robert Kiyosaki",
    "model": "Paperback",
    "type": "",
    "name": "Rich Dad Poor Dad",
    "price": 9.99,
    "image": "assets/Books/3.jpg",
    "description": "A fundamental book on personal finance and wealth building.",
    "rating": 4.2,
    "reviews": 355,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "books-4",
    "slug": "books-blackbook-english-vocabulary-4",
    "category": "Books",
    "product": "Book",
    "brand": "Nikhil Gupta",
    "model": "Paperback",
    "type": "",
    "name": "Blackbook of English Vocabulary",
    "price": 8.75,
    "image": "assets/Books/4.jpg",
    "description": "An essential guide to mastering English vocabulary for competitive exams.",
    "rating": 4.9,
    "reviews": 402,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "books-5",
    "slug": "books-robin-sharma-5",
    "category": "Books",
    "product": "Book",
    "brand": "Robin Sharma",
    "model": "Hardcover",
    "type": "",
    "name": "The Everyday Hero Manifesto",
    "price": 14.99,
    "image": "assets/Books/5.jpg",
    "description": "A powerful guide to unlocking your personal genius and living an extraordinary life.",
    "rating": 4.7,
    "reviews": 449,
    "stock": "In stock",
    "discount": 15
  },
  {
    "id": "books-6",
    "slug": "books-think-straight-6",
    "category": "Books",
    "product": "Book",
    "brand": "Darius Foroux",
    "model": "Paperback",
    "type": "",
    "name": "Think Straight",
    "price": 11.25,
    "image": "assets/Books/6.jpg",
    "description": "Change your thoughts and change your life with this practical guide.",
    "rating": 4.5,
    "reviews": 496,
    "stock": "Limited stock",
    "discount": 27
  },
  {
    "id": "books-7",
    "slug": "books-the-alchemist-7",
    "category": "Books",
    "product": "Book",
    "brand": "Paulo Coelho",
    "model": "Paperback",
    "type": "",
    "name": "The Alchemist",
    "price": 9.5,
    "image": "assets/Books/7.jpg",
    "description": "A beloved philosophical novel about finding your personal legend.",
    "rating": 4.3,
    "reviews": 543,
    "stock": "In stock",
    "discount": 12
  },
  {
    "id": "books-8",
    "slug": "books-a-good-girls-guide-8",
    "category": "Books",
    "product": "Book",
    "brand": "Holly Jackson",
    "model": "Paperback",
    "type": "",
    "name": "A Good Girl's Guide to Murder",
    "price": 24.99,
    "image": "assets/Books/8.jpg",
    "description": "A gripping young adult mystery novel.",
    "rating": 4.1,
    "reviews": 590,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "books-9",
    "slug": "books-energize-your-mind-9",
    "category": "Books",
    "product": "Book",
    "brand": "Gaur Gopal Das",
    "model": "Paperback",
    "type": "",
    "name": "Energize Your Mind",
    "price": 13.75,
    "image": "assets/Books/9.jpg",
    "description": "Learn the art of mastering your thoughts, feelings, and emotions.",
    "rating": 4.8,
    "reviews": 637,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "books-10",
    "slug": "books-anxiety-10",
    "category": "Books",
    "product": "Book",
    "brand": "A.B. Katmore",
    "model": "Paperback",
    "type": "",
    "name": "Anxiety",
    "price": 10.99,
    "image": "assets/Books/10.jpg",
    "description": "An insightful exploration of anxiety and navigating mental emotional wellness.",
    "rating": 4.6,
    "reviews": 684,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "books-11",
    "slug": "books-the-book-11",
    "category": "Books",
    "product": "Book",
    "brand": "Oliver Pötzsch",
    "model": "Paperback",
    "type": "",
    "name": "The Book",
    "price": 7.99,
    "image": "assets/Books/11.jpg",
    "description": "An international bestselling historical thriller.",
    "rating": 4.4,
    "reviews": 731,
    "stock": "Limited stock",
    "discount": 15
  },
  {
    "id": "books-12",
    "slug": "books-death-an-inside-story-12",
    "category": "Books",
    "product": "Book",
    "brand": "Sadhguru",
    "model": "Hardcover",
    "type": "",
    "name": "Death: An Inside Story",
    "price": 9.25,
    "image": "assets/Books/12.jpg",
    "description": "A deep and insightful look into the process of death.",
    "rating": 4.2,
    "reviews": 778,
    "stock": "In stock",
    "discount": 27
  },
  {
    "id": "speakers-Speakers-1",
    "slug": "speakers-bose-soundlink-revolve-Speakers-1",
    "category": "Speakers",
    "product": "Speaker",
    "brand": "Bose",
    "model": "SoundLink Revolve",
    "type": "",
    "name": "Bose SoundLink Revolve",
    "price": 199.99,
    "image": "assets/speakers/1.jpg",
    "description": "A portable Bluetooth speaker with 360-degree sound and long battery life.",
    "rating": 4.9,
    "reviews": 261,
    "stock": "Limited stock",
    "discount": 12
  },
  {
    "id": "speakers-Speakers-2",
    "slug": "speakers-sonos-one-sl-Speakers-2",
    "category": "Speakers",
    "product": "Speaker",
    "brand": "Sonos",
    "model": "One SL",
    "type": "",
    "name": "Sonos One SL",
    "price": 179,
    "image": "assets/speakers/2.jpg",
    "description": "A compact speaker with rich sound and the ability to pair with other Sonos speakers.",
    "rating": 4.7,
    "reviews": 308,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "speakers-Speakers-3",
    "slug": "speakers-jbl-flip-5-Speakers-3",
    "category": "Speakers",
    "product": "Speaker",
    "brand": "JBL",
    "model": "Flip 5",
    "type": "",
    "name": "JBL Flip 5",
    "price": 119.99,
    "image": "assets/speakers/3.jpg",
    "description": "A waterproof portable speaker with powerful bass and vibrant colors.",
    "rating": 4.5,
    "reviews": 355,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "speakers-Speakers-4",
    "slug": "speakers-sony-srs-xb43-Speakers-4",
    "category": "Speakers",
    "product": "Speaker",
    "brand": "Sony",
    "model": "SRS-XB43",
    "type": "",
    "name": "Sony SRS-XB43",
    "price": 169.5,
    "image": "assets/speakers/4.jpg",
    "description": "A high-powered Bluetooth speaker with extra bass and built-in party lights.",
    "rating": 4.3,
    "reviews": 402,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "speakers-Speakers-5",
    "slug": "speakers-ultimate-ears-megaboom-3-Speakers-5",
    "category": "Speakers",
    "product": "Speaker",
    "brand": "Ultimate Ears",
    "model": "MEGABOOM 3",
    "type": "",
    "name": "Ultimate Ears MEGABOOM 3",
    "price": 199,
    "image": "assets/speakers/5.jpg",
    "description": "A rugged and waterproof speaker with 360-degree sound and customizable EQ.",
    "rating": 4.1,
    "reviews": 449,
    "stock": "In stock",
    "discount": 15
  },
  {
    "id": "speakers-Speakers-6",
    "slug": "speakers-harman-kardon-aura-studio-3-Speakers-6",
    "category": "Speakers",
    "product": "Speaker",
    "brand": "Harman Kardon",
    "model": "Aura Studio 3",
    "type": "",
    "name": "Harman Kardon Aura Studio 3",
    "price": 249.99,
    "image": "assets/speakers/6.jpg",
    "description": "A visually striking speaker with ambient lighting and powerful audio quality.",
    "rating": 4.8,
    "reviews": 496,
    "stock": "Limited stock",
    "discount": 27
  },
  {
    "id": "speakers-Speakers-7",
    "slug": "speakers-anker-soundcore-flare-Speakers-7",
    "category": "Speakers",
    "product": "Speaker",
    "brand": "Anker",
    "model": "Soundcore Flare",
    "type": "",
    "name": "Anker Soundcore Flare",
    "price": 69.99,
    "image": "assets/speakers/7.jpg",
    "description": "A portable speaker with 360-degree sound, customizable lighting, and IPX7 waterproof rating.",
    "rating": 4.6,
    "reviews": 543,
    "stock": "In stock",
    "discount": 12
  },
  {
    "id": "speakers-Speakers-8",
    "slug": "speakers-marshall-stanmore-ii-Speakers-8",
    "category": "Speakers",
    "product": "Speaker",
    "brand": "Marshall",
    "model": "Stanmore II",
    "type": "",
    "name": "Marshall Stanmore II",
    "price": 349,
    "image": "assets/speakers/8.jpg",
    "description": "A vintage-styled speaker with classic rock aesthetics and powerful audio output.",
    "rating": 4.4,
    "reviews": 590,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "speakers-Speakers-9",
    "slug": "speakers-bose-home-speaker-500-Speakers-9",
    "category": "Speakers",
    "product": "Speaker",
    "brand": "Bose",
    "model": "Home Speaker 500",
    "type": "",
    "name": "Bose Home Speaker 500",
    "price": 299,
    "image": "assets/speakers/9.jpg",
    "description": "A smart speaker with voice control and spacious sound, suitable for home audio.",
    "rating": 4.2,
    "reviews": 637,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "speakers-Speakers-10",
    "slug": "speakers-yamaha-musiccast-20-Speakers-10",
    "category": "Speakers",
    "product": "Speaker",
    "brand": "Yamaha",
    "model": "MusicCast 20",
    "type": "",
    "name": "Yamaha MusicCast 20",
    "price": 199.5,
    "image": "assets/speakers/10.jpg",
    "description": "A wireless speaker with multi-room audio support and clear sound quality.",
    "rating": 4.9,
    "reviews": 684,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "speakers-Speakers-11",
    "slug": "speakers-bang-and-olufsen-beoplay-a9-Speakers-11",
    "category": "Speakers",
    "product": "Speaker",
    "brand": "Bang & Olufsen",
    "model": "Beoplay A9",
    "type": "",
    "name": "Bang & Olufsen Beoplay A9",
    "price": 2799,
    "image": "assets/speakers/11.jpg",
    "description": "A high-end wireless speaker with a distinctive design and exceptional sound.",
    "rating": 4.7,
    "reviews": 731,
    "stock": "Limited stock",
    "discount": 15
  },
  {
    "id": "speakers-Speakers-12",
    "slug": "speakers-ue-boom-2-Speakers-12",
    "category": "Speakers",
    "product": "Speaker",
    "brand": "UE",
    "model": "BOOM 2",
    "type": "",
    "name": "UE BOOM 2",
    "price": 129.99,
    "image": "assets/speakers/12.jpg",
    "description": "A portable Bluetooth speaker with rugged design, 360-degree sound, and waterproofing.",
    "rating": 4.5,
    "reviews": 778,
    "stock": "In stock",
    "discount": 27
  },
  {
    "id": "tv-1",
    "slug": "tv-samsung-crystal-1",
    "category": "TV",
    "product": "TV",
    "brand": "Samsung",
    "model": "Crystal 4K",
    "type": "",
    "name": "Samsung Crystal 4K UHD",
    "price": 1999,
    "image": "assets/TV/1.jpg",
    "description": "A high-end 4K TV with stunning picture quality and smart features.",
    "rating": 4.3,
    "reviews": 261,
    "stock": "Limited stock",
    "discount": 12
  },
  {
    "id": "tv-2",
    "slug": "tv-lg-4k-uhd-2",
    "category": "TV",
    "product": "TV",
    "brand": "LG",
    "model": "4K UHD TV",
    "type": "",
    "name": "LG 4K UHD Smart TV",
    "price": 1499,
    "image": "assets/TV/2.jpg",
    "description": "A 4K LED TV with advanced processing and immersive audio technology.",
    "rating": 4.1,
    "reviews": 308,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "tv-3",
    "slug": "tv-samsung-wondertainment-3",
    "category": "TV",
    "product": "TV",
    "brand": "Samsung",
    "model": "Wondertainment",
    "type": "",
    "name": "Samsung Wondertainment TV",
    "price": 1799.99,
    "image": "assets/TV/3.jpg",
    "description": "A smart TV with vibrant colors and impressive upscaling capabilities.",
    "rating": 4.8,
    "reviews": 355,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "tv-4",
    "slug": "tv-hisense-vivid-tv-4",
    "category": "TV",
    "product": "TV",
    "brand": "Hisense",
    "model": "VIVID TV",
    "type": "",
    "name": "Hisense VIVID TV",
    "price": 799,
    "image": "assets/TV/4.jpg",
    "description": "An affordable 4K TV with DTS Virtual X and Google TV built-in.",
    "rating": 4.6,
    "reviews": 402,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "tv-5",
    "slug": "tv-akai-smart-tv-5",
    "category": "TV",
    "product": "TV",
    "brand": "Akai",
    "model": "Smart TV",
    "type": "",
    "name": "Akai Smart TV",
    "price": 1199.5,
    "image": "assets/TV/5.jpg",
    "description": "A highly capable smart TV with immersive entertainment features.",
    "rating": 4.4,
    "reviews": 449,
    "stock": "In stock",
    "discount": 15
  },
  {
    "id": "tv-6",
    "slug": "tv-panasonic-4k-6",
    "category": "TV",
    "product": "TV",
    "brand": "Panasonic",
    "model": "4K HDR",
    "type": "",
    "name": "Panasonic 4K HDR TV",
    "price": 999,
    "image": "assets/TV/6.jpg",
    "description": "A beautiful 4K TV with impressive contrast and support for HDR formats.",
    "rating": 4.2,
    "reviews": 496,
    "stock": "Limited stock",
    "discount": 27
  },
  {
    "id": "tv-7",
    "slug": "tv-xiaomi-5a-40-7",
    "category": "TV",
    "product": "TV",
    "brand": "Xiaomi",
    "model": "Smart TV 5A 40",
    "type": "",
    "name": "Xiaomi Smart TV 5A 40\"",
    "price": 2499.99,
    "image": "assets/TV/7.jpg",
    "description": "A sleek Xiaomi smart TV bringing cinematic picture quality to your living room.",
    "rating": 4.9,
    "reviews": 543,
    "stock": "In stock",
    "discount": 12
  },
  {
    "id": "tv-8",
    "slug": "tv-mi-5x-43-8",
    "category": "TV",
    "product": "TV",
    "brand": "Xiaomi",
    "model": "5X 4K 43",
    "type": "",
    "name": "Mi TV 5X 4K 43\"",
    "price": 1499,
    "image": "assets/TV/8.jpg",
    "description": "A highly responsive 4K Mi TV with advanced connectivity and metal bezelless design.",
    "rating": 4.7,
    "reviews": 590,
    "stock": "In stock",
    "discount": 18
  },
  {
    "id": "tv-9",
    "slug": "tv-xiaomi-5a-43-9",
    "category": "TV",
    "product": "TV",
    "brand": "Xiaomi",
    "model": "Smart TV 5A 43",
    "type": "",
    "name": "Xiaomi Smart TV 5A 43\"",
    "price": 999.99,
    "image": "assets/TV/9.jpg",
    "description": "A 43-inch Xiaomi smart TV with excellent viewing angles and vivid display.",
    "rating": 4.5,
    "reviews": 637,
    "stock": "In stock",
    "discount": 22
  },
  {
    "id": "tv-10",
    "slug": "tv-oneplus-android-10",
    "category": "TV",
    "product": "TV",
    "brand": "OnePlus",
    "model": "Android TV",
    "type": "",
    "name": "OnePlus 4K Android TV",
    "price": 299.5,
    "image": "assets/TV/10.jpg",
    "description": "An affordable full HD TV with a familiar Android UI for seamless streaming.",
    "rating": 4.3,
    "reviews": 684,
    "stock": "In stock",
    "discount": 8
  },
  {
    "id": "tv-11",
    "slug": "tv-toshiba-vidaa-11",
    "category": "TV",
    "product": "TV",
    "brand": "Toshiba",
    "model": "VIDAA TV",
    "type": "",
    "name": "Toshiba TV Powered by VIDAA",
    "price": 349,
    "image": "assets/TV/11.png",
    "description": "A sharp, budget-friendly 4K TV powered by the fast and intuitive VIDAA OS.",
    "rating": 4.1,
    "reviews": 731,
    "stock": "Limited stock",
    "discount": 15
  },
  {
    "id": "tv-12",
    "slug": "tv-kodak-smart-12",
    "category": "TV",
    "product": "TV",
    "brand": "Kodak",
    "model": "Smart TV",
    "type": "",
    "name": "Kodak Smart TV",
    "price": 1499,
    "image": "assets/TV/12.jpg",
    "description": "A vibrant digital smart TV perfect for movie nights and console gaming.",
    "rating": 4.8,
    "reviews": 778,
    "stock": "In stock",
    "discount": 27
  }
] satisfies Array<Omit<Product, "image"> & { image: string }>;

export const products: Product[] = rawProducts.map((product) => ({
  ...product,
  image: assetUrl(product.image),
}));

export const categories = Array.from(new Set(products.map((product) => product.category)));

export const featuredProducts = products.filter((_, index) => index % 7 === 0).slice(0, 10);
